---
v2:
  metadata:
    title: "HPC Cluster"
  login:
    host: "frontend"
  job:
    adapter: "slurm"
    cluster: "hpc"
    bin: "/usr/bin"
    conf: "/etc/slurm/slurm.conf"
  batch_connect:
    vnc:
      script_wrapper: |
        export PATH="/opt/TurboVNC/bin:$PATH"
        export WEBSOCKIFY_CMD="/usr/bin/websockify"
        %s
  custom:
    xdmod:
      resource_id: 1
